### ISSUE TITLE
Add addition test coverage

### ISSUE THREAD

**Issue by kamuda1** [arfc/annsa#33]
- Tests for simple functions
    - [ ] Identify simple 
    - [ ] Create tests for simple functions
</br>

- Tests for overly complicated functions 
    - [ ] Identify overly complicated functions 
    - [ ] Into simple functions
    - [ ] Create tests for these functions
</br>

- Issue can be closed when annsa has 80% test coverage.
    - [ ] 80% test coverage

**Comment by katyhuff** [comment]
Note: The way that the tests are written now, they're more like integraton tests than unit tests. Please review the testing chapter of the book, the [python-testing tutorial](http://katyhuff.github.io/python-testing/) I have written, and perhaps check out some tests in pyrk for examples of how to test code one function at a time (with assertions)...

**Comment by kamuda1** [comment]
Test coverage added throughout.
