### ISSUE TITLE
Straggling comments

### ISSUE THREAD

**Issue by katyhuff** [arfc/annsa#56]
I didn't review #52 quickly enough to point out that [in annsa/load_templates.py at line 54][https://github.com/samgdotson/annsa/blob/7319b5c00085bd4922bf5029aaaf70e99b103602/annsa/load_templates.py#L54), the following should not have been merged. In the future, this should be an open issue in github. It should not be a comment cluttering up the source code and committed to master.

```python
        #ASSERT
        #Add an assertion if the argument is misspelled or incorrect.
        #It should throw an error saying "hey this isn't an option."
        #Will make debugging easier if your error is that normaheight
        #isn't normalheight.
```

This issue can be closed with a PR that removes the comment and adds the desired assertion (actually, I'd recommend an exception, not an assertion.)

**Comment by samgdotson** [comment]
Removed straggling comment
